### ISSUE TITLE
Doesn't seem to work with Safari

### ISSUE THREAD

**Issue by 34code** [stimulus-components/stimulus-scroll-to#2]
Version 15.1 (17612.2.9.1.20)
on
MacOS 12.0.1 (Monterey)

**Comment by 34code** [comment]
nvm did not read docs properly - as per docs below:

"For now, Safari does not provide smooth behavior scroll support."

**Comment by rwtaylor** [comment]
I'm confused about this.
When I add Stimulus ScrollTo to my rails project the smooth scroll works in Chrome, but not in Safari.
However, when I go to the demo site smooth scroll does work in Safari!
Is the demo not using the Window.scrollTo() method?

**Comment by guillaumebriday** [comment]
The polyfill is loaded in the demo 👍  https://github.com/stimulus-components/stimulus-scroll-to/blob/master/index.html#L13
