### ISSUE TITLE
Fallback to default event execution if target wasn't found

### ISSUE THREAD

**Issue by k0va1** [stimulus-components/stimulus-scroll-to#4]
I'm using a navbar with links on different pages in my app, but scroll-to action is only needed on the home page where there lots of anchors. On other pages these links should work as regular links I suppose. Here https://github.com/stimulus-components/stimulus-scroll-to/blob/master/src/index.ts#L31 we're preventing all default events hence links don't work anymore if there were not found any target

I suggest to call `scrollTo` function only in case of having target and fallback to default behavior if not. WDYT?

**Comment by guillaumebriday** [comment]
Hum, I'm not sure to understand why add this controller on an anchor without target?

If you still have the issue, please reopen it on the main repo: https://github.com/stimulus-components/stimulus-components
